### ISSUE TITLE
Duplicate data in (action)

### ISSUE THREAD

**Issue by BkMiguel12** [peterfreeman/ngx-dropzone#33] opened 2019-09-04 01:02 UTC
Hi @peterfreeman !

First... amazing component!

I want to do something like this:
`onFileChange(event) {

      for(let i=0; i<event.addedFiles.length; i++) {
        if(event.addedFiles[i].type == 'image/jpeg') {
          this.files.push(event.addedFiles[i]);
        } else {
          this.pdfs.push(event.addedFiles[i]);
        }
      }

    console.log(this.files);
    console.log(this.pdfs);

`
And that works but It's like executing the function assigned to (change) twice

**Comment by zauni** [comment] 2019-09-05 14:11
Have the same issue. It looks like the change event is also emitted from the `<input>` element and then you have two events, but just one with the "addedFiles" attribute.

And that is probably also the same problem as in #32.

**Comment by peterfreeman** [comment] 2019-09-05 14:34
Duplicate of #32

**Closed by peterfreeman** 2019-09-05 14:34 UTC
